### ISSUE TITLE
no hand detection

### ISSUE THREAD

**Issue by m3m3-chan** [maxzuo/handGestureRecognizer#1]
Hi, 
Thanks for sharing this interesting repo!
I wanted to try the finger count demo you have but when I run "presentation.py" I'm not getting a proper output.
I'm running the code on Py3 Windows machine . I have fixed the compatibility issue and I can see the code is running and taking finger values but it seldom shows any output and when it does it's not the hand and it stays for a second and disappears.

any solution?

Thanks,

**Comment by maxzuo** [comment]
Hey m3m3-chan,

This repo was created for a specific task. It requires the wearer to be wearing a bright green band. Quite honestly, this is a very old repo of mine and not great. A lot of the stuff is hardcoded and should be using ML.

If you would like to do some simple hand gesture recognition with OpenCV I suggest you use **haar cascades**. Past that you would want to be dealing with instance segmentation and machine learning classification.

I appreciate your interest in my repo and I hope this will help you the best.

Best of luck with your project!
M

**Comment by m3m3-chan** [comment]
@maxzuo  Thanks for the response!
